name: Pre-merge checks

on:
  pull_request:
    branches:
      - main
      - "releases/**"

permissions: {}

jobs:
  zizmor-scan-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Run Zizmor scan
        uses: open-edge-platform/anomalib/.github/actions/security/zizmor@fb7d494bf61c3806fb6497d435c7dcabd2ce8e04
        with:
          scan-scope: "changed"
          severity-level: "MEDIUM"
          confidence-level: "HIGH"
          fail-on-findings: true
  bandit-scan-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Run Bandit scan
        uses: open-edge-platform/anomalib/.github/actions/security/bandit@fb7d494bf61c3806fb6497d435c7dcabd2ce8e04
        with:
          scan-scope: "changed"
          severity-level: "MEDIUM"
          confidence-level: "HIGH"
          config_file: ".github/bandit_config.yml"
          fail-on-findings: true
